# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gridCCDr <- function(cors, init_betas, nn, nj, lambdas, params, verbose) {
    .Call('ccdr_gridCCDr', PACKAGE = 'ccdr', cors, init_betas, nn, nj, lambdas, params, verbose)
}

singleCCDr <- function(cors, init_betas, nn, nj, lambda, params, verbose) {
    .Call('ccdr_singleCCDr', PACKAGE = 'ccdr', cors, init_betas, nn, nj, lambda, params, verbose)
}

